[package]
name = "rogue-digger"
version = "0.1.0"
authors = ["daniil <daniil2305@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.4.0"
bracket-lib = "0.8.1"